name: Update Quote Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
      - uses: ApoorvTyagi/quote-readme@main
        with:
          OPTION: both 
